ikaazhar/KADA

app/controllers/UserController.php
app/models/User.php
app/views/auth/login_ahli.php
app/views/auth/login_alk.php
app/views/auth/login_staff.php
public/index.php

updated controller and model

---

app/controllers/UserController.php
app/models/User.php
app/views/users/family_details.php
public/index.php

form part family details (updated)

update membership application

---

app/views/users/family_details.php
public/index.php

tadi x tambah kat router ni dh tambah

edited membership application

---

app/views/menu/saving.php

done interface saving without function

---

app/views/menu/saving.php

update ubah interface saving

---

app/controllers/UserController.php
app/models/User.php
app/views/users/family_details.php

Table kt form tu da bole print family detail yg dah dimasukkan

Dah betulkan table kt form

---

app/controllers/UserController.php
app/models/User.php
app/views/auth/homepage.php
public/index.php

UPDATE LOGIN MEMBER

---

app/controllers/UserController.php
app/models/User.php
app/views/auth/buttonpage.php
app/views/auth/homepage.php
app/views/auth/login_staff.php
app/views/menu_admin/homepage_admin.php
public/index.php

Modify admin login functions to match new table and create homepage for admin with admin features, only interface for now

Admin login and homepage

---

app/controllers/UserController.php
app/models/User.php
app/views/auth/homepage.php
public/index.php

tekan button add alk kt homepage kalau nk add row. ni just utk backend je nnti kene delete

edit login alk

---

app/controllers/UserController.php
app/models/User.php
app/views/auth/login_alk.php
app/views/menu_admin/homepage_admin.php
app/views/menu_admin/viewLoanForm.php
app/views/menu_admin/viewLoanList.php
public/index.php

betulkan login admin sikit dgn buat reviewed function utk staff. sori lupa tukar branch hihih

Reviewed form utk staff

---

app/controllers/UserController.php
app/core/Model.php
app/models/User.php
app/views/menu_admin/viewLoanForm.php
app/views/menu_alk/homepage_alk.php
app/views/menu_alk/viewReviewedLoan.php
public/index.php

Add functions to approve loan for alk and delete some old useless functions

alk approve loan

---

app/controllers/UserController.php
app/models/User.php
app/views/menu_member/homepage_ahli.php
app/views/menu_member/invoice.php
app/views/menu_member/saving.php
public/index.php

Show saving interface & show invoice interface function
- this part is done by Damiya tp since Damiya punya github x boleh nak pull request utk save the work so terpaksa guna laptop ika

Savingfunction interface

---

app/controllers/UserController.php
app/models/User.php

ada table baru yg simpan member_id from memberlogin table and id_number form member_application

tambah table member info

---

app/views/auth/buttonpage.php
app/views/auth/homepage.php
app/views/auth/login_ahli.php
app/views/auth/login_alk.php
app/views/auth/login_staff.php
app/views/menu_member/homepage_ahli.php
app/views/menu_member/invoice.php

buttonpage view, homepage view, login ahli view, login alk view, login admin view, homepage_ahli view and invoice view

done styling few part

---

app/views/menu_member/homepage_ahli.php

tukar navbar homepage ahli

---

app/core/Model.php
app/views/menu_admin/homepage_admin.php

bootstrap dh settle, ni button2 yg ada
*senarai pemohon member
*senarai pemohon loan
*report

bootstrap staff - homepage

---

app/views/menu_member/viewPersonalInfo.php

edit personal info button and tukar bahasa skit

tambah skit

---

app/views/menu_alk/approve_member_application.php
app/views/menu_alk/viewReviewedLoan.php

tukar router bg image je sbb salah

view reviewed loan application design

---

app/controllers/UserController.php
app/core/Model.php
app/views/menu_admin/annual_reportAdmin.php
app/views/menu_admin/homepage_admin.php
app/views/menu_admin/review_member_application.php
app/views/menu_admin/viewLoanForm.php
app/views/menu_admin/viewLoanList.php
app/views/menu_admin/viewMemberForm.php
app/views/menu_alk/annual_report.php
public/index.php

Bootstrap staff report

---

app/controllers/UserController.php
app/models/User.php
app/views/menu_admin/addNewALK.php
app/views/menu_admin/addNewAdmin.php
app/views/menu_admin/homepage_admin.php
app/views/menu_admin/successAddAdmin.php
public/index.php

add some new view files, modify model and controllers function to let admin be able to add new admin or alk

done add admin & alk

---

app/controllers/UserController.php
app/models/User.php
app/views/menu_admin/annual_reportAdmin.php
app/views/menu_alk/annual_report.php

* tambah report terminate application
- admin
- alk

tambah report
